version: "3.4"

networks:
  netapi-newtwork:
    driver: bridge

services:
  weatherforecast.api:
    image: ${DOCKER_REGISTRY-}webapi
    depends_on:
      - "weatherforecast_db"
    container_name: weatherforecast-api
    ports:
      - "8088:83"
      - "443"
    build:
      context: .
      dockerfile: Presentation.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ConnectionStrings__DatabaseConnection=Host=weatherforecast_db;Port=5432;Database=weatherforecastDB;User ID=postgres;Password=postgres;Pooling=true;Include Error Detail=true"

  weatherforecast_db:
    image: postgres
    container_name: weatherforecast_db
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weatherforecast
    volumes:
      - weather-data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.17
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8009:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

    networks:
      - netapi-newtwork

volumes:
  weather-data:
  pgadmin-data:
